global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: quarkus
    metrics_path: /q/metrics
    static_configs:
      - targets: [ 'localhost:8080' ]

  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
